### ISSUE TITLE
JDK bug prevent invoking default method

### ISSUE THREAD

**Issue by hohwille** [m-m-m/bean#4]
Java reflection should allow to invoke default methods from interfaces if they are exported by the declaring module.
However we discovered that the bug https://bugs.openjdk.java.net/browse/JDK-8209078[JDK-8209078] is marked as resolved but is still not properly fixed (tested with latest Java 15).
The bug even persists if you declare the module as `open` that contains the interface with the default method.

As a workaround we log an error and emulate the method in dynamic proxy so we are not entirely blocked:
https://github.com/m-m-m/bean/blob/3ad408e86ad21241bb79b5d82433387d7238e6bb/factory/src/main/java/io/github/mmm/bean/factory/impl/operation/BeanOperation.java#L139

However, this prevents the custom configuration that is intendet via the default method implementation.
We hope that JDK developers will be able to fix this severe bug.

**Comment by hohwille** [comment]
https://stackoverflow.com/questions/37812393/how-to-explicitly-invoke-default-method-from-a-dynamic-proxy

**Comment by hohwille** [comment]
https://github.com/eclipse-openj9/openj9/issues/3851
https://github.com/eclipse-openj9/openj9/pull/3978/files

**Comment by hohwille** [comment]
So I see no other solution than using `InvocationHandler.invokeDefault` what requires Java 16 so we would technically migrate our entire codebase to Java 17 making it impossible to use with Java < 16.
While this is fine for `bean` and above modules, it is IMHO inacceptable for repositories such as:
* base
* event
* value
* scanner
* code
* binary
* cli
* nls

**Comment by hohwille** [comment]
Maybe a good solution could be the following:
* keep source and target level on Java 11
* use Java17 in `bean` repo (for GHA, etc.) and accordingly repos dependening on it
* write the code such that `InvocationHandler.invokeDefault` is used but try to catch MethodNotFoundException and keep the old implementation as fallback.

**Comment by hohwille** [comment]
I tested this new feature https://bugs.openjdk.java.net/browse/JDK-8263045

Still Java is buggy or flawed:
```
java.lang.IllegalArgumentException: Failed to create bean of type io.github.mmm.bean.test.ContactBean
	at io.github.mmm.bean/io.github.mmm.bean.impl.BeanFactoryManager.create(BeanFactoryManager.java:51)
	at io.github.mmm.bean/io.github.mmm.bean.BeanFactory.create(BeanFactory.java:27)
	at io.github.mmm.bean.test/io.github.mmm.bean.test.BeanFactoryImplTest.testCreateFromInterfaceWithInheritance(BeanFactoryImplTest.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:84)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:768)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.IllegalStateException: Failed to create property Age from default method public default io.github.mmm.property.number.integers.IntegerProperty io.github.mmm.bean.test.ContactBean.Age()
	at io.github.mmm.bean.factory/io.github.mmm.bean.factory.impl.operation.BeanOperationProperty.createProperty(BeanOperationProperty.java:45)
	at io.github.mmm.bean.factory/io.github.mmm.bean.factory.impl.proxy.BeanProxyPrototype.initProperties(BeanProxyPrototype.java:68)
	at io.github.mmm.bean.factory/io.github.mmm.bean.factory.impl.proxy.BeanProxyPrototype.<init>(BeanProxyPrototype.java:59)
	at io.github.mmm.bean.factory/io.github.mmm.bean.factory.impl.proxy.BeanProxyPrototype.lambda$0(BeanProxyPrototype.java:190)
	at io.github.mmm.bean.factory/io.github.mmm.bean.factory.impl.MemoryCache.lambda$0(MemoryCache.java:46)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at io.github.mmm.bean.factory/io.github.mmm.bean.factory.impl.MemoryCache.get(MemoryCache.java:46)
	at io.github.mmm.bean.factory/io.github.mmm.bean.factory.impl.proxy.BeanProxyPrototype.get(BeanProxyPrototype.java:190)
	at io.github.mmm.bean.factory/io.github.mmm.bean.factory.impl.proxy.BeanProxyPrototype.get(BeanProxyPrototype.java:180)
	at io.github.mmm.bean.factory/io.github.mmm.bean.factory.impl.BeanFactoryImpl.create(BeanFactoryImpl.java:44)
	at io.github.mmm.bean/io.github.mmm.bean.impl.BeanFactoryManager.create(BeanFactoryManager.java:39)
	... 69 more
Caused by: java.lang.IllegalAccessException: class io.github.mmm.bean.factory.impl.operation.BeanOperationProperty (in module io.github.mmm.bean.factory) cannot access interface io.github.mmm.bean.test.ContactBean (in module io.github.mmm.bean.test) because module io.github.mmm.bean.test does not export io.github.mmm.bean.test to module io.github.mmm.bean.factory
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
	at java.base/java.lang.reflect.InvocationHandler.invokeDefault(InvocationHandler.java:278)
	at io.github.mmm.bean.factory/io.github.mmm.bean.factory.impl.operation.BeanOperationProperty.createProperty(BeanOperationProperty.java:40)
	... 79 more
```

So `InvocationHandler.invokeDefault` still fails for a default method in a public interface that I can create a proxy for but am not allowed to invoke that default method.
This JPMS is a complete desaster - things are overregulated and become unusable.
Is there anything we can do about this?

**Comment by hohwille** [comment]
So for Java16+ all is solved now. The issue with the stacktrace from the last comment was because the package was not exported by the test module. When it is exported, the module does not have to be declared as open. So we have a working result now and the fallback behaviour for java < 16 still gives some basic support and according WARNING log-messages.

Therefore we can consider this issue as fixed:
* beans from any module on your modulepath can be instantiated via `BeanFactory` if they are inside an exported package. This seems a fair and suitable requirement for beans.
* default methods are working both as factory method to create/inject the initial property for a property method as well as for regular (non-property) methods (behaving just like any other default method in an interface).
* it should be possible to make the same work also for bean-generator so the same will also work inside TeaVM or GraalVM.
